


http://localhost:3000/almacen/almacen

###

POST http://localhost:3000//carrito/almacen-llegada 
content-type: 'application/json'

{
   {
            id: 4,
            codigo_local: "P004",
            codigo_externo: "4444",
            nombre: "Tester De Medir Voltage",
            cantidad: 100,
            cantidad_minima: 3.00,
            ubicacion_tramo: "T1F3",
            detalles: "Nota:",
            fecha_registro: "2023-08-27",
            peso: 0.50,
            id_calidad_producto: 1,
            precio_compra: 600.00,
            id_marca: 1,
            id_garantia: 2,
            id_proveedor: 41,
            id_unidad_medida: 1,
            id_impuestos: 1,
            porciento_beneficio: 24,
            id_venta_detallada: 2,
            dimenciones: "2.5X6",
            id_condicion_producto: 1,
            ventas_sin_stock: true,
            categoria: "Herramientas Eléctricas",
            imagen: 'https://images.unsplash.com/photo-1710194572710-bbd92a2d3f9c?q=80&w=987&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'
          },
          {
            id: 2,
            codigo_local: "P002",
            codigo_externo: "22222",
            nombre: "Pala De Corte",
            cantidad: 100,
            cantidad_minima: 4.00,
            ubicacion_tramo: "T1F1",
            detalles: "Nota:",
            fecha_registro: "2023-08-25",
            peso: 5.00,
            id_calidad_producto: 1,
            precio_compra: 1800.00,
            id_marca: 1,
            id_garantia: 2,
            id_proveedor: 40,
            id_unidad_medida: 1,
            id_impuestos: 1,
            porciento_beneficio: 35,
            id_venta_detallada: 2,
            dimenciones: "40X8",
            id_condicion_producto: 1,
            ventas_sin_stock: true,
            categoria: "Herramientas de Jardín",
            imagen:'https://images.unsplash.com/photo-1651197227940-60c9d32f89e7?q=80&w=987&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'
    }
}
###


###

http://localhost:3000/almacen/almacen
